# This is a basic workflow to help you get started with Actions

name: Test LinuxUpdate

# Controls when the action will run.
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ubuntu_check:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install bash sudo

      - name: Run ./LinuxUpdate.sh
        run: ./LinuxUpdate.sh

  arch_check:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # https://github.com/qutebrowser/qutebrowser/commit/478e4de7bd1f26bebdcdc166d5369b2b5142c3e2
      - name: Workaround glibc issue
        run: |
          patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst && \
          curl -LO "https://repo.archlinuxcn.org/x86_64/$patched_glibc" && \
          bsdtar -C / -xvf "$patched_glibc"

      - name: Install prerequisites
        run: |
          pacman -Syyu --noconfirm
          pacman -S sudo reflector --noconfirm

      - name: Run ./LinuxUpdate.sh
        run: ./LinuxUpdate.sh
